# SRRArch Simulator

A simulator for a custom Instruction Set Architecture (ISA) designed for learning purposes. This simulator loads ELF files generated by an LLVM-based compiler backend and executes them in a simulated environment.

## Features

- Loads and executes ELF binaries

## Building

### Prerequisites

- CMake 3.15+
- C++17 compiler (GCC 9+, Clang 10+)

### Build Instructions

```bash
# Clone the repository
git clone https://github.com/steven6798/SRRArch-simulator.git
cd SRRArch-simulator

# Build
mkdir build && cd build
cmake .. -DLLVM_DIR=/path/to/llvm/lib/cmake/llvm
make -j$(nproc)